### ISSUE TITLE
Not able to install neural_renderer

### ISSUE THREAD

**Issue by gargijoshii** [XingangPan/GAN2Shape#201]
>pip install git+https://github.com/daniilidis-group/neural_renderer.git
Collecting git+https://github.com/daniilidis-group/neural_renderer.git
  Cloning https://github.com/daniilidis-group/neural_renderer.git to c:\users\gargij~1\appdata\local\temp\pip-req-build-lza236t5
  Running command git clone -q https://github.com/daniilidis-group/neural_renderer.git 'C:\Users\GARGIJ~1\AppData\Local\Temp\pip-req-build-lza236t5'
  Resolved https://github.com/daniilidis-group/neural_renderer.git to commit b2a1e6ce16a54f94f26f86fe1dc3814637e15251
    ERROR: Command errored out with exit status 1:
     command: 'C:\Apps\anaconda\envs\gan_env\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GARGIJ~1\\AppData\\Local\\Temp\\pip-req-build-lza236t5\\setup.py'"'"'; __file__='"'"'C:\\Users\\GARGIJ~1\\AppData\\Local\\Temp\\pip-req-build-lza236t5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\GARGIJ~1\AppData\Local\Temp\pip-pip-egg-info-jd21ab5_'
         cwd: C:\Users\GARGIJ~1\AppData\Local\Temp\pip-req-build-lza236t5\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\GARGIJ~1\AppData\Local\Temp\pip-req-build-lza236t5\setup.py", line 4, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding git+https://github.com/daniilidis-group/neural_renderer.git. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by agr78** [comment]
You may need to install `pytorch` first. I installed `pytorch 1.2.0` but still needed to use [a modified version of this solution](https://github.com/daniilidis-group/neural_renderer/issues/67) from the [`neural_render`](https://github.com/daniilidis-group/neural_renderer/) repository to install it.

```
conda install gxx_linux-64=9.4
git clone https://github.com/dellshan/neural_renderer.git
python setup.py install
```
