### ISSUE TITLE
mmcv version 

### ISSUE THREAD

**Issue by bharathCoitor** [XingangPan/GAN2Shape#41]
i am using google colab 
pytorch =1.2.0
cuda=9.2

i have faced error like
Traceback (most recent call last):
  File "/content/drive/My Drive/Colab Notebooks/GAN2Shape-main/run.py", line 7, in <module>
    from mmcv.runner import init_dist
  File "/usr/local/lib/python3.7/dist-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/usr/local/lib/python3.7/dist-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/usr/local/lib/python3.7/dist-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/__init__.py", line 40, in <module>
    from .hub import load_url
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/hub.py", line 20, in <module>
    from torch.hub import HASH_REGEX, _get_torch_home, download_url_to_file
ImportError: cannot import name 'download_url_to_file' from 'torch.hub' (/usr/local/lib/python3.7/dist-packages/torch/hub.py)

so kindly suggest any way to proceed,
thank you.

**Comment by agr78** [comment]
I resolved this by replacing `line 20` in `~/anaconda3/envs/gan2shape/lib/python3.6/site-packages/mmcv/utils/hub.py` to
```python
from torch.hub import HASH_REGEX, _get_torch_home, _download_url_to_file
```
Then I needed to install a few more missing packages,  `ipython` and `tqdm`
Also there was a missing library file, `libcblas.so.3`, needed by `scipy` , requiring `libatlas-base-dev`. Hope this helps.
